#!/bin/bash
# Clobber most bsps, leaving cpc, cpc64, arm, mips and ppc

rm -rf	bsp/amcc_*				\
	bsp/apple_powermac_g5_64/		\
	bsp/broadcom_bcm91250a_64/		\
	bsp/cav_octeon*				\
	bsp/common_pc_64_kvm_guest/		\
	bsp/emer_atca7101/			\
	bsp/fsl_imx*				\
	bsp/fsl_8548cds/			\
	bsp/fsl_mpc8*				\
	bsp/fsl_p2020/				\
	bsp/fsl_p102*				\
	bsp/hp_proliant_bl460c/			\
	bsp/intel_*				\
	bsp/lsi_app3300/			\
	bsp/mindspeed_c*			\
	bsp/nlm_xls_atx_64_be/			\
	bsp/qemu_*				\
	bsp/ti_*				\
	bsp/wrs_sbc85x0/
