#!/bin/bash
# Clobber most bsps, leaving cpc, cpc64, arm, mips and ppc

rm -rf	amcc_*				\
	apple_powermac_g5_64/		\
	broadcom_bcm91250a_64/		\
	cav_octeon*			\
	common_pc_64_kvm_guest/		\
	emer_atca7101/			\
	fsl_imx*			\
	fsl_8548cds/			\
	fsl_mpc8*			\
	fsl_p2020/			\
	fsl_p102*			\
	hp_proliant_bl460c/		\
	intel_*				\
	lsi_app3300/			\
	mindspeed_c*			\
	nlm_xls_atx_64_be/		\
	qemu_*				\
	ti_*				\
	wrs_sbc85x0/
