#!/bin/bash

# rr-cache will be in the build, one level above 'linux', need
# to arrange this to get under the tree if this is to be autodone
# by others.
if [ -d "../rr-cache" ]; then
  if [ -d ".git/rr-cache" ]; then
        cp -r ../rr-cache/* .git/rr-cache
  else
        cp -r ../rr-cache .git
  fi
fi
if [ -d "wrs/cfg/kernel-*-cache/rr-cache" ]; then
  if [ -d ".git/rr-cache" ]; then
        cp -r wrs/cfg/kernel-*-cache/rr-cache .git/rr-cache
  else
        cp -r wrs/cfg/kernel-*-cache/rr-cache .git
  fi
fi

