#!/bin/bash

# rr-cache will be in the build, one level above 'linux', need
# to arrange this to get under the tree if this is to be autodone
# by others.
if [ -d "../rr-cache" ]; then
  cp -r ../rr-cache .git/
fi
